import { Schema, model, models, Model, Types } from "mongoose";
import { MATCH_EVENT_TYPES, type MatchEventType } from "@/lib/constants";

export { MATCH_EVENT_TYPES };
export type { MatchEventType };

/**
 * Something that happened in a match. Events are never deleted: a wrong one is voided
 * (with reason and author) so the history stays auditable, and scores/discipline are recomputed.
 */
export interface IMatchEvent {
  _id: Types.ObjectId;
  matchId: Types.ObjectId;
  championshipId: Types.ObjectId;
  /** Team of the player the event refers to (for an own goal, the team that conceded it). */
  teamId: Types.ObjectId;
  /** Scorer, carded player or the player leaving the pitch on a substitution. */
  playerId?: Types.ObjectId;
  /** Assisting player on a goal, or the player entering on a substitution. */
  relatedPlayerId?: Types.ObjectId;
  type: MatchEventType;
  minute: number;
  note?: string;
  /** Generated by a rule (second yellow -> red) instead of typed by the operator. */
  auto: boolean;
  /** For an automatic red: the yellow that caused it. */
  linkedEventId?: Types.ObjectId;
  /** Yellow cards that produced a sending-off do not count toward accumulation. */
  countsForAccumulation: boolean;
  voided: boolean;
  voidedAt?: Date;
  voidedBy?: string;
  voidReason?: string;
  recordedBy: string;
  createdAt: Date;
  updatedAt: Date;
}

const MatchEventSchema = new Schema<IMatchEvent>(
  {
    matchId: { type: Schema.Types.ObjectId, ref: "Match", required: true },
    championshipId: { type: Schema.Types.ObjectId, ref: "Championship", required: true },
    teamId: { type: Schema.Types.ObjectId, ref: "Team", required: true },
    playerId: { type: Schema.Types.ObjectId, ref: "Player" },
    relatedPlayerId: { type: Schema.Types.ObjectId, ref: "Player" },
    type: { type: String, enum: MATCH_EVENT_TYPES, required: true },
    minute: { type: Number, required: true, min: 0, max: 150 },
    note: { type: String, trim: true, maxlength: 300 },
    auto: { type: Boolean, default: false },
    linkedEventId: { type: Schema.Types.ObjectId, ref: "MatchEvent" },
    countsForAccumulation: { type: Boolean, default: true },
    voided: { type: Boolean, default: false },
    voidedAt: { type: Date },
    voidedBy: { type: String },
    voidReason: { type: String, trim: true },
    recordedBy: { type: String, required: true },
  },
  { timestamps: true }
);

MatchEventSchema.index({ matchId: 1, minute: 1, createdAt: 1 });
MatchEventSchema.index({ championshipId: 1, playerId: 1, type: 1 });

export const MatchEvent: Model<IMatchEvent> =
  (models.MatchEvent as Model<IMatchEvent>) || model<IMatchEvent>("MatchEvent", MatchEventSchema);
